---
title: "CFPB dash"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(lubridate)
library(janitor)
library(glue)
library(plotly)
library(tidyr)
library(DT)



```

Column {data-width=650}
-----------------------------------------------------------------------

### Distribution of Months; DEC saw the most claims

```{r}
complains<- readRDS("complaints.rds")
complains
#

comp <- separate(complains,date_received,c("Year", "Month","Day"), sep = "-")
comp
Mar<- comp %>% 
  filter(Month == "03")
Apr <- comp %>% 
  filter(Month == "04")
May <- comp %>% 
  filter(Month == "05")
Jun <- comp %>% 
  filter(Month == "06")
Jul <- comp %>% 
  filter(Month == "07")
Aug <- comp %>% 
  filter(Month == "08")
Sep <- comp %>% 
  filter(Month == "09")
Oct <- comp %>% 
  filter(Month == "10")
Nov <- comp %>% 
  filter(Month == "11")
Dec <- comp %>% 
  filter(Month == "12")

countmar <- count(Mar)
countapr <- count(Apr)
countmay <- count(May)
countjun <- count(Jun)
countjul <- count(Jul)
countaug <- count(Aug)
countsep <- count(Sep)
countoct <- count(Oct)
countnov <- count(Nov)
countdec <- count(Dec)
thetable<- table(c(countmar,countapr, countmay, countjun, countjul, countaug, countsep, countnov, countdec))


```

Column {data-width=350}
-----------------------------------------------------------------------

### Distributions of states; FL had the most

```{r}
comp %>% 
  select(state)

countstate <-comp %>% 
  count(state)
```

### Responses; most were closed with an explanation; fewest colsed with monetary relief

```{r}
expl<- comp %>% 
  filter(company_response_to_consumer=="Closed with explanation")
count<-expl
nomoney<- comp %>% 
  filter(company_response_to_consumer=="Closed with non-monetary relief")
count<-nomoney
yesmoney<- comp %>% 
  filter(company_response_to_consumer=="Closed with monetary relief")
count<-yesmoney

```

